name: 🚀 Deploy WordPress vía FTP/SFTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP/SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:     ${{ secrets.FTP_SERVER }}
          username:   ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          protocol:   ${{ secrets.FTP_PROTOCOL }}   # ftp
          port:       ${{ secrets.FTP_PORT }}       # 21
          local-dir:  ./                             # ruta local de tu repo
          server-dir: /                              # raíz en el servidor (/public_html)
          dry-run:    false

      - name: Confirmar despliegue
        if: success()
        run: echo "✅ Despliegue completado correctamente"
