name: 🚀 Deploy WordPress vía FTPS

on:
  push:
    branches:
      - main

jobs:
  ftps-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:     ${{ secrets.FTP_SERVER }}
          username:   ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          protocol:   ftps          # FTPS explícito (TLS)
          port:       21            # puerto FTPS explícito
          local-dir:  ./            # raíz del repo
          server-dir: /             # apunta a /home/malagons/public_html
          dry-run:    false

      - name: Confirmar despliegue
        if: success()
        run: echo "✅ Despliegue completado correctamente"
